target 'APCDController', :exclusive => true do
  pod "APCDController", :path => "../"
end

target 'APCDController_Tests', :exclusive => true do
  pod "APCDController", :path => "../"
  pod 'OCMock'
  pod 'Expecta'
end
